name: Splunk_AppInspect
permissions:
  contents: read

on:
  push:
    branches-ignore: [main]
    
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  APPSDIR: /master-apps

jobs:
  splunk_appinspect:
    runs-on: ubuntu-latest

    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Get AppInspect  
        run: pip install splunk-appinspect

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AppInspect Version
        run: splunk-appinspect list version

      - name: Run AppInspect
        shell: bash
        run: |
          EXIT_CODE=0
          for app in `git diff ${{ github.event.pull_request.base.sha }} ${{ github.sha }} --name-only --diff-filter=ACMRT | grep "^\${{ env.APPSDIR }}" | sed -n -e 's|^\(${{ env.APPSDIR }}/[^/]*\).*|\1|p' | sort -u`; do
            if [ -d $app ]; then
              echo "::group::Inspecting $app..."
              splunk-appinspect inspect --excluded-tags cloud --custom-checks-dir script/appinspect/rules $app
              if [ $? -gt 0 ]; then
                EXIT_CODE=255
              fi
              echo "::endgroup::"
            fi
          done
          exit $EXIT_CODE
